[build]
  publish = "site"
  command = "mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  MKDOCS_ENABLE_INSIDER = "true"

[context.deploy-preview.environment]
  MKDOCS_ENABLE_INSIDER = "false"
