name: Deploy Documentation

on:
  push:
    branches:
      - feature-testing
      - main
  pull_request:
    branches:
      - feature-testing
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        pip install mkdocs-material
        pip install pymdown-extensions
        
    - name: Build documentation
      run: |
        mkdocs build --strict
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/feature-testing' || github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages
        force_orphan: true
        
    - name: Deploy to Netlify (Alternative)
      if: github.ref == 'refs/heads/feature-testing' || github.ref == 'refs/heads/main'
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './site'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
