name: Test Workflow

on:
  push:
    branches:
      - feature-testing
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test Step
      run: |
        echo "✅ GitHub Actions is working!"
        echo "Current time: $(date)"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
